### ISSUE TITLE
error during setup of scanner

### ISSUE THREAD

**Issue by moustafak** [mozilla/http-observatory#113]
Tested on:
Ubuntu 16.04 (fresh install)

Following the documentation, performing the following command yields some errors
pip3 install -r requirements.txt

`Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 1006, in check_if_exists
    self.satisfied_by = pkg_resources.get_distribution(str(no_marker))
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 535, in get_distribution
    dist = get_provider(dist)
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 415, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 695, in find
    raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (beautifulsoup4 4.4.1 (/usr/lib/python3/dist-packages), Requirement.parse('beautifulsoup4==4.5.1'))` 

To fix I had to run the following command:
sudo pip3 install --upgrade pip

**Comment by marumari** [comment]
That's odd; is beautifulsoup installed by default in Ubuntu 16?

**Comment by moustafak** [comment]
Hi April,

Thanks for the follow-up on this.

Bs4 is installed by default with version 4.4.1-1

Looking at the error it complains of a version mismatch where version 4.5.1 seems to be required.

Thanks,
Moustafa

**Comment by marumari** [comment]
Err, are you having problems with this?  It does need to be setup with the proper requirements as listed.  :)

**Comment by moustafak** [comment]
Thanks for all your help with it, April.

Please close this ticket.

Regards,
Moustafa
