### ISSUE TITLE
docker-compose up fails

### ISSUE THREAD

**Issue by ssx** [mozilla/http-observatory#233]
Hi,

I'm encountering the following error when running the docker image version of this:

```
httpobservatory_redis_1 is up-to-date
Recreating httpobservatory_postgres_1 ... 
Recreating httpobservatory_postgres_1 ... done
Recreating httpobservatory_scanner_1 ... 
Recreating httpobservatory_website_1 ... 
Recreating httpobservatory_scanner_1
Recreating httpobservatory_website_1 ... error

Recreating httpobservatory_scanner_1 ... done

ERROR: for website  Cannot start service website: oci runtime error: container_linux.go:247: starting container process caused "exec: \"uwsgi\": executable file not found in $PATH"
ERROR: Encountered errors while bringing up the project.
```

Current docker version is:
`Docker version 17.05.0-ce-rc1, build 2878a85`

Current docker-compose version is:
`docker-compose version 1.13.0-rc1, build 38af513`

**Comment by ssx** [comment]
Logs from Docker attached:

[logs.txt](https://github.com/mozilla/http-observatory/files/956419/logs.txt)

**Comment by floatingatoll** [comment]
If you add `uwsgi` to the requirements list of the Dockerfile, does that fix it?

**Comment by ssx** [comment]
that did indeed allow it to run, which produced this error:
```
scanner_1   | Traceback (most recent call last):
scanner_1   |   File "/usr/local/lib/python3.5/site-packages/celery/app/utils.py", line 355, in find_app
scanner_1   |     sym = symbol_by_name(app, imp=imp)
scanner_1   |   File "/usr/local/lib/python3.5/site-packages/celery/bin/base.py", line 506, in symbol_by_name
scanner_1   |     return imports.symbol_by_name(name, imp=imp)
scanner_1   |   File "/usr/local/lib/python3.5/site-packages/kombu/utils/imports.py", line 61, in symbol_by_name
scanner_1   |     return getattr(module, cls_name) if cls_name else module
scanner_1   | AttributeError: module 'httpobs.scanner' has no attribute 'tasks'
scanner_1   | 
scanner_1   | During handling of the above exception, another exception occurred:
scanner_1   | 
scanner_1   | Traceback (most recent call last):
scanner_1   |   File "/usr/local/bin/celery", line 11, in <module>
scanner_1   |     sys.exit(main())
scanner_1   |   File "/usr/local/lib/python3.5/site-packages/celery/__main__.py", line 14, in main
scanner_1   |     _main()
scanner_1   |   File "/usr/local/lib/python3.5/site-packages/celery/bin/celery.py", line 326, in main
scanner_1   |     cmd.execute_from_commandline(argv)
scanner_1   |   File "/usr/local/lib/python3.5/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
scanner_1   |     super(CeleryCommand, self).execute_from_commandline(argv)))
scanner_1   |   File "/usr/local/lib/python3.5/site-packages/celery/bin/base.py", line 279, in execute_from_commandline
scanner_1   |     argv = self.setup_app_from_commandline(argv)
scanner_1   |   File "/usr/local/lib/python3.5/site-packages/celery/bin/base.py", line 481, in setup_app_from_commandline
scanner_1   |     self.app = self.find_app(app)
scanner_1   |   File "/usr/local/lib/python3.5/site-packages/celery/bin/base.py", line 503, in find_app
scanner_1   |     return find_app(app, symbol_by_name=self.symbol_by_name)
scanner_1   |   File "/usr/local/lib/python3.5/site-packages/celery/app/utils.py", line 358, in find_app
scanner_1   |     sym = imp(app)
scanner_1   |   File "/usr/local/lib/python3.5/site-packages/celery/utils/imports.py", line 101, in import_from_cwd
scanner_1   |     return imp(module, package=package)
scanner_1   |   File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
scanner_1   |     return _bootstrap._gcd_import(name[level:], package, level)
scanner_1   |   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
scanner_1   |   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
scanner_1   |   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
scanner_1   |   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
scanner_1   |   File "<frozen importlib._bootstrap_external>", line 673, in exec_module
scanner_1   |   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
scanner_1   |   File "/app/httpobs/scanner/tasks.py", line 5, in <module>
scanner_1   |     from httpobs.database import (insert_test_results,
scanner_1   |   File "/app/httpobs/database/__init__.py", line 1, in <module>
scanner_1   |     from .database import (get_cursor,
scanner_1   |   File "/app/httpobs/database/database.py", line 16, in <module>
scanner_1   |     from httpobs.scanner.analyzer import NUM_TESTS
scanner_1   |   File "/app/httpobs/scanner/analyzer/__init__.py", line 1, in <module>
scanner_1   |     from .content import contribute, subresource_integrity
scanner_1   |   File "/app/httpobs/scanner/analyzer/content.py", line 2, in <module>
scanner_1   |     from publicsuffixlist import PublicSuffixList
scanner_1   | ImportError: No module named 'publicsuffixlist'
httpobservatory_scanner_1 exited with code 1
```

**Comment by april** [comment]
I wonder if this is something that got broken when we split up the requirements files?

**Comment by floatingatoll** [comment]
Hmm, yeah, that might be possible.

**Comment by ssx** [comment]
If you'd like me to test out a previous commit with where you think it'll be working, I'll be happy to do so 👍

**Comment by floatingatoll** [comment]
There should be one commit that splits up requirements.txt into a bunch of
new files, testing before/after that specific commit would confirm April's
theory.

**Comment by ssx** [comment]
Commit 1a2682339b9e37db428d7a3bee22aa955eadb958 seems to be running okay - will test more later today and let you know.

**Comment by ssx** [comment]
When issuing a POST to http://localhost:57001/api/v1/analyze, it's giving an error of "scanner-backend-not-available-try-again-soon" so I'll need to dig into that. 👍

**Comment by april** [comment]
Okay!  Thanks for working so hard on this!

**Comment by ssx** [comment]
I looked a little more into it, everything looks to be running apart from the scanner component, I'll paste you the logs shortly.

**Comment by ssx** [comment]
Apologies this took so long, but here's the relevant out of the scanner dying:

```
redis_1     | 1:C 03 May 07:36:05.658 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
janitor_1   | Retrieving the Google HSTS Preload list
redis_1     |                 _._                                                  
janitor_1   | WARNING: Unable to connect to PostgreSQL.
redis_1     |            _.-``__ ''-._                                             
postgres_1  | The files belonging to this database system will be owned by user "postgres".
scanner_1   | Traceback (most recent call last):
redis_1     |       _.-``    `.  `_.  ''-._           Redis 3.2.8 (00000000/0) 64 bit
postgres_1  | This user must also own the server process.
scanner_1   |   File "/usr/local/lib/python3.5/site-packages/celery/app/utils.py", line 355, in find_app
redis_1     |   .-`` .-```.  ```\/    _.,_ ''-._                                   
postgres_1  | 
janitor_1   | celery beat v3.1.23 (Cipater) is starting.
scanner_1   |     sym = symbol_by_name(app, imp=imp)
redis_1     |  (    '      ,       .-`  | `,    )     Running in standalone mode
backend_1   | *** Starting uWSGI 2.0.12 (64bit) on [Wed May  3 07:36:18 2017] ***
scanner_1   |   File "/usr/local/lib/python3.5/site-packages/celery/bin/base.py", line 506, in symbol_by_name
postgres_1  | The database cluster will be initialized with locale "en_US.utf8".
frontend_1  | *** Starting uWSGI 2.0.12 (64bit) on [Wed May  3 07:36:30 2017] ***
janitor_1   | Traceback (most recent call last):
janitor_1   |   File "/usr/local/lib/python3.5/site-packages/kombu/transport/__init__.py", line 80, in resolve_transport
redis_1     |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
redis_1     |  |    `-._   `._    /     _.-'    |     PID: 1
scanner_1   |     return imports.symbol_by_name(name, imp=imp)
frontend_1  | compiled with version: 4.9.2 on 02 May 2017 08:22:03
backend_1   | compiled with version: 4.9.2 on 02 May 2017 08:22:03
janitor_1   |     transport = TRANSPORT_ALIASES[transport]
redis_1     |   `-._    `-._  `-./  _.-'    _.-'                                   
redis_1     |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
redis_1     |  |    `-._`-._        _.-'_.-'    |           http://redis.io        
postgres_1  | The default database encoding has accordingly been set to "UTF8".
postgres_1  | The default text search configuration will be set to "english".
postgres_1  | 
janitor_1   | KeyError: ''
frontend_1  | os: Linux-4.9.21-moby #1 SMP Wed Apr 12 01:18:47 UTC 2017
frontend_1  | nodename: 28d57b0c518c
redis_1     |   `-._    `-._`-.__.-'_.-'    _.-'                                   
scanner_1   |   File "/usr/local/lib/python3.5/site-packages/kombu/utils/imports.py", line 61, in symbol_by_name
postgres_1  | Data page checksums are disabled.
janitor_1   | 
janitor_1   | During handling of the above exception, another exception occurred:
backend_1   | os: Linux-4.9.21-moby #1 SMP Wed Apr 12 01:18:47 UTC 2017
redis_1     |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
scanner_1   |     return getattr(module, cls_name) if cls_name else module
postgres_1  | 
frontend_1  | machine: x86_64
janitor_1   | 
janitor_1   | Traceback (most recent call last):
backend_1   | nodename: b019542e8ed8
backend_1   | machine: x86_64
scanner_1   | AttributeError: module 'httpobs.scanner' has no attribute 'tasks'
frontend_1  | clock source: unix
redis_1     |  |    `-._`-._        _.-'_.-'    |                                  
redis_1     |   `-._    `-._`-.__.-'_.-'    _.-'                                   
janitor_1   |   File "/usr/local/bin/celery", line 11, in <module>
janitor_1   |     sys.exit(main())
backend_1   | clock source: unix
frontend_1  | pcre jit disabled
postgres_1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
redis_1     |       `-._    `-.__.-'    _.-'                                       
scanner_1   | 
janitor_1   |   File "/usr/local/lib/python3.5/site-packages/celery/__main__.py", line 30, in main
backend_1   | pcre jit disabled
frontend_1  | detected number of CPU cores: 2
postgres_1  | creating subdirectories ... ok
redis_1     |           `-._        _.-'                                           
scanner_1   | During handling of the above exception, another exception occurred:
janitor_1   |     main()
backend_1   | detected number of CPU cores: 2
frontend_1  | current working directory: /app
redis_1     |               `-.__.-'                                               
scanner_1   | 
janitor_1   |   File "/usr/local/lib/python3.5/site-packages/celery/bin/celery.py", line 81, in main
backend_1   | current working directory: /app
frontend_1  | detected binary path: /usr/local/bin/uwsgi
redis_1     | 
postgres_1  | selecting default max_connections ... 100
scanner_1   | Traceback (most recent call last):
janitor_1   |     cmd.execute_from_commandline(argv)
backend_1   | detected binary path: /usr/local/bin/uwsgi
frontend_1  | your memory page size is 4096 bytes
scanner_1   |   File "/usr/local/bin/celery", line 11, in <module>
janitor_1   |   File "/usr/local/lib/python3.5/site-packages/celery/bin/celery.py", line 793, in execute_from_commandline
backend_1   | your memory page size is 4096 bytes
postgres_1  | selecting default shared_buffers ... 128MB
redis_1     | 1:M 03 May 07:36:05.664 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
frontend_1  | detected max file descriptor number: 1048576
scanner_1   |     sys.exit(main())
janitor_1   |     super(CeleryCommand, self).execute_from_commandline(argv)))
backend_1   | detected max file descriptor number: 1048576
redis_1     | 1:M 03 May 07:36:05.664 # Server started, Redis version 3.2.8
scanner_1   |   File "/usr/local/lib/python3.5/site-packages/celery/__main__.py", line 14, in main
janitor_1   |   File "/usr/local/lib/python3.5/site-packages/celery/bin/base.py", line 311, in execute_from_commandline
backend_1   | lock engine: pthread robust mutexes
frontend_1  | lock engine: pthread robust mutexes
postgres_1  | selecting dynamic shared memory implementation ... posix
scanner_1   |     _main()
janitor_1   |     return self.handle_argv(self.prog_name, argv[1:])
backend_1   | thunder lock: disabled (you can enable it with --thunder-lock)
redis_1     | 1:M 03 May 07:36:05.664 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
frontend_1  | thunder lock: disabled (you can enable it with --thunder-lock)
scanner_1   |   File "/usr/local/lib/python3.5/site-packages/celery/bin/celery.py", line 326, in main
redis_1     | 1:M 03 May 07:36:05.664 * The server is now ready to accept connections on port 6379
postgres_1  | creating configuration files ... ok
janitor_1   |   File "/usr/local/lib/python3.5/site-packages/celery/bin/celery.py", line 785, in handle_argv
backend_1   | uWSGI http bound on :57002 fd 4
scanner_1   |     cmd.execute_from_commandline(argv)
janitor_1   |     return self.execute(command, argv)
backend_1   | uwsgi socket 0 bound to TCP address 127.0.0.1:41111 (port auto-assigned) fd 3
scanner_1   |   File "/usr/local/lib/python3.5/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
frontend_1  | uWSGI http bound on :57001 fd 4
janitor_1   |   File "/usr/local/lib/python3.5/site-packages/celery/bin/celery.py", line 717, in execute
postgres_1  | running bootstrap script ... ok
backend_1   | Python version: 3.5.3 (default, Apr 25 2017, 05:02:51)  [GCC 4.9.2]
scanner_1   |     super(CeleryCommand, self).execute_from_commandline(argv)))
frontend_1  | uwsgi socket 0 bound to TCP address 127.0.0.1:43185 (port auto-assigned) fd 3
janitor_1   |     ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
scanner_1   |   File "/usr/local/lib/python3.5/site-packages/celery/bin/base.py", line 279, in execute_from_commandline
frontend_1  | Python version: 3.5.3 (default, Apr 25 2017, 05:02:51)  [GCC 4.9.2]
postgres_1  | performing post-bootstrap initialization ... ok
janitor_1   |   File "/usr/local/lib/python3.5/site-packages/celery/bin/base.py", line 315, in run_from_argv
backend_1   | *** Python threads support is disabled. You can enable it with --enable-threads ***
scanner_1   |     argv = self.setup_app_from_commandline(argv)
frontend_1  | *** Python threads support is disabled. You can enable it with --enable-threads ***
janitor_1   |     sys.argv if argv is None else argv, command)
postgres_1  | syncing data to disk ... 
backend_1   | Python main interpreter initialized at 0x1d6bbf0
scanner_1   |   File "/usr/local/lib/python3.5/site-packages/celery/bin/base.py", line 481, in setup_app_from_commandline
frontend_1  | Python main interpreter initialized at 0x23bbbf0
janitor_1   |   File "/usr/local/lib/python3.5/site-packages/celery/bin/base.py", line 377, in handle_argv
postgres_1  | WARNING: enabling "trust" authentication for local connections
backend_1   | your server socket listen backlog is limited to 100 connections
scanner_1   |     self.app = self.find_app(app)
frontend_1  | your server socket listen backlog is limited to 100 connections
janitor_1   |     return self(*args, **options)
postgres_1  | You can change this by editing pg_hba.conf or using the option -A, or
backend_1   | your mercy for graceful operations on workers is 60 seconds
scanner_1   |   File "/usr/local/lib/python3.5/site-packages/celery/bin/base.py", line 503, in find_app
frontend_1  | your mercy for graceful operations on workers is 60 seconds
janitor_1   |   File "/usr/local/lib/python3.5/site-packages/celery/bin/base.py", line 274, in __call__
postgres_1  | --auth-local and --auth-host, the next time you run initdb.
scanner_1   |     return find_app(app, symbol_by_name=self.symbol_by_name)
janitor_1   |     ret = self.run(*args, **kwargs)
backend_1   | mapped 145536 bytes (142 KB) for 1 cores
scanner_1   |   File "/usr/local/lib/python3.5/site-packages/celery/app/utils.py", line 358, in find_app
frontend_1  | mapped 145536 bytes (142 KB) for 1 cores
janitor_1   |   File "/usr/local/lib/python3.5/site-packages/celery/bin/beat.py", line 79, in run
postgres_1  | ok
backend_1   | *** Operational MODE: single process ***
scanner_1   |     sym = imp(app)
frontend_1  | *** Operational MODE: single process ***
janitor_1   |     return beat().run()
postgres_1  | 
scanner_1   |   File "/usr/local/lib/python3.5/site-packages/celery/utils/imports.py", line 101, in import_from_cwd
janitor_1   |   File "/usr/local/lib/python3.5/site-packages/celery/apps/beat.py", line 83, in run
backend_1   | Retrieving the Google HSTS Preload list
postgres_1  | Success. You can now start the database server using:
scanner_1   |     return imp(module, package=package)
janitor_1   |     self.start_scheduler()
postgres_1  | 
postgres_1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
janitor_1   |   File "/usr/local/lib/python3.5/site-packages/celery/apps/beat.py", line 104, in start_scheduler
scanner_1   |   File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
postgres_1  | 
backend_1   | WARNING: Unable to connect to PostgreSQL.
janitor_1   |     c.reset(self.startup_info(beat)))))
scanner_1   |     return _bootstrap._gcd_import(name[level:], package, level)
janitor_1   |   File "/usr/local/lib/python3.5/site-packages/celery/apps/beat.py", line 127, in startup_info
scanner_1   |   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
janitor_1   |     conninfo=self.app.connection().as_uri(),
janitor_1   |   File "/usr/local/lib/python3.5/site-packages/celery/app/base.py", line 386, in connection
janitor_1   |     'BROKER_CONNECTION_TIMEOUT', connect_timeout
janitor_1   |   File "/usr/local/lib/python3.5/site-packages/kombu/connection.py", line 165, in __init__
janitor_1   |     if not get_transport_cls(transport).can_parse_url:
backend_1   | Loading the HTTP Observatory Backend
scanner_1   |   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
postgres_1  | waiting for server to start....LOG:  could not bind IPv6 socket: Cannot assign requested address
janitor_1   |   File "/usr/local/lib/python3.5/site-packages/kombu/transport/__init__.py", line 109, in get_transport_cls
scanner_1   |   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
scanner_1   |   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
scanner_1   |   File "<frozen importlib._bootstrap_external>", line 673, in exec_module
scanner_1   |   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
scanner_1   |   File "/app/httpobs/scanner/tasks.py", line 5, in <module>
scanner_1   |     from httpobs.database import (insert_test_results,
scanner_1   |   File "/app/httpobs/database/__init__.py", line 1, in <module>
scanner_1   |     from .database import (get_cursor,
scanner_1   |   File "/app/httpobs/database/database.py", line 16, in <module>
scanner_1   |     from httpobs.scanner.analyzer import NUM_TESTS
scanner_1   |   File "/app/httpobs/scanner/analyzer/__init__.py", line 1, in <module>
scanner_1   |     from .content import contribute, subresource_integrity
scanner_1   |   File "/app/httpobs/scanner/analyzer/content.py", line 2, in <module>
scanner_1   |     from publicsuffixlist import PublicSuffixList
scanner_1   | ImportError: No module named 'publicsuffixlist'
```

Hopefully that's helpful.

**Comment by cduranleau** [comment]
Will be digging in soon, but I'm running into the same problem with the latest commit in master: https://github.com/mozilla/http-observatory/commit/8b85fb4a6a3acec6178a9755bc335ee198445e01

**Comment by cduranleau** [comment]
{code}M1711995:http-observatory cd033922$ git diff origin/master
diff --git a/.gitignore b/.gitignore
index 2598fbb..0935627 100644
--- a/.gitignore
+++ b/.gitignore
@@ -6,3 +6,4 @@
 __pycache__
 *.py[oc]
 /venv
+.DS_Store
\ No newline at end of file
diff --git a/httpobs/Dockerfile b/httpobs/Dockerfile
index 22cb570..490ed38 100644
--- a/httpobs/Dockerfile
+++ b/httpobs/Dockerfile
@@ -10,10 +10,10 @@ RUN install -o app -g app -d /var/run/httpobs /var/log/httpobs
 WORKDIR /app
 
 COPY requirements.txt /app
+COPY . httpobs
 
 RUN pip install --upgrade --no-cache-dir -r requirements.txt
 
-COPY . httpobs
 ENV PYTHONPATH $PYTHONPATH:/app
 
 USER app
\ No newline at end of file
diff --git a/httpobs/requirements.txt b/httpobs/requirements.txt
index 2a05b3b..871c516 100644
--- a/httpobs/requirements.txt
+++ b/httpobs/requirements.txt
@@ -19,3 +19,6 @@ pyflakes==1.5.0
 pytz==2017.2
 vine==1.1.3
 Werkzeug==0.12.1
+-r httpobs/database/requirements.txt
+-r httpobs/scanner/requirements.txt
+-r httpobs/website/requirements.txt
diff --git a/requirements.txt b/requirements.txt
index 591a6a8..ac25e3a 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -1,4 +1 @@
 -r httpobs/requirements.txt
--r httpobs/database/requirements.txt
--r httpobs/scanner/requirements.txt
--r httpobs/website/requirements.txt
M1711995:http-observatory cd033922$ 
{code}

Solves the problem. Might not be the best way because just re-creates the 'requirements.txt' structure inside the docker container.

**Comment by cduranleau** [comment]
PR: https://github.com/mozilla/http-observatory/pull/243
